name: Contiguous-Integration 

permissions:
  contents: read

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name:  >-
      CI
      ${{ matrix.os }}
      ${{ matrix.compiler }}
      ${{ matrix.build-type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc, gcc, clang]
        os: [windows-latest, macos-latest, ubuntu-latest]
        build-type: [Debug, Profile, Release]
        exclude:
        - os: windows-latest
          compiler: gcc   
        - os: windows-latest
          compiler: clang
        - os: macos-latest
          compiler: msvc
        - os: macos-latest
          compiler: gcc
        - os: ubuntu-latest
          compiler: msvc
        include:
        - compiler: clang
          CC: clang
          CXX: clang++
        - compiler: msvc
          CC: 
          CXX: 
        - compiler: gcc
          CC: gcc
          CXX: g++
        - os: windows-latest
          CMAKE_PRESET: windows-build
          SETUP_FILE: Setup.bat
        - os: ubuntu-latest
          CMAKE_PRESET: linux-build
          SETUP_FILE: Setup.sh
        - os: macos-latest
          CMAKE_PRESET: macos-build
          SETUP_FILE: Setup.command

    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/Build
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      CMAKE_C_COMPILER: ${{ matrix.CC }}
      CMAKE_CXX_COMPILER: ${{ matrix.CXX }}
      SETUP_FILE: ${{ matrix.SETUP_FILE }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        clean: true

    - name: Setup
      run: |
        ./${{ env.SETUP_FILE }}

    - name: Configuring projects
      run: >-
        cmake
        -S "${{ github.workspace }}/Engine"
        -B "${{ env.CMAKE_BUILD_DIR }}" 
        --preset ${{ matrix.CMAKE_PRESET }}
        -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}/install_test/

    - name: Build
      run: >-
        cmake --build "${{ env.CMAKE_BUILD_DIR }}" --config "${{ matrix.build-type }}"
