name: Contiguous-Integration 

permissions:
  contents: read

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name:  >-
      Configure
      ${{ matrix.os }}
      ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc, gcc, clang]
        os: [windows-latest, macos-latest, ubuntu-latest]
        exclude:
        - os: windows-latest
          compiler: gcc   
        - os: windows-latest
          compiler: clang
        - os: macos-latest
          compiler: msvc
        - os: macos-latest
          compiler: gcc
        - os: ubuntu-latest
          compiler: msvc
        include:
        - compiler: clang
          CC: clang
          CXX: clang++
        - compiler: msvc
          CC: cl
          CXX: cl
        - compiler: gcc
          CC: gcc
          CXX: g++
        - os: windows-latest
          CMAKE_PRESET: windows-build
          SETUP_FILE: Setup.bat
          CMAKE_GENERATOR: Visual Studio 17 2022
          TOOLCHAIN_FILE: Windows-PC.cmake
        - os: ubuntu-latest
          CMAKE_PRESET: linux-build
          SETUP_FILE: Setup.sh
          CMAKE_GENERATOR: Ninja Multi-Config
          TOOLCHAIN_FILE: Linux-PC.cmake
        - os: macos-latest
          CMAKE_PRESET: macos-build
          SETUP_FILE: Setup.command
          CMAKE_GENERATOR: Xcode
          TOOLCHAIN_FILE: macOS-PC.cmake

    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/Build
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      CMAKE_C_COMPILER: ${{ matrix.CC }}
      CMAKE_CXX_COMPILER: ${{ matrix.CXX }}
      SETUP_FILE: ${{ matrix.SETUP_FILE }}
      TOOLCHAIN: ${{ github.workspace }}/Engine/Build/CMake/Toolchain/${{ matrix.TOOLCHAIN_FILE }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        clean: true

    - name: Setup
      run: |
        ./${{ env.SETUP_FILE }}

    - name: Configuring projects
      run: >-
        cmake
        -S "${{ github.workspace }}/Engine"
        -B "${{ env.CMAKE_BUILD_DIR }}" 
        -G "${{ matrix.CMAKE_GENERATOR }}"
        --toolchain "${{ env.TOOLCHAIN }}"
        -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}/install_test/

    - name: Check files
      shell: bash
      run: |
        ls -la ${{ env.CMAKE_BUILD_DIR }}

    - name: Build (Debug)
      run: >-
        cmake --build "${{ env.CMAKE_BUILD_DIR }}" --config Debug

    - name: Build (Profile)
      run: >-
        cmake --build "${{ env.CMAKE_BUILD_DIR }}" --config Profile

    - name: Build (Release)
      run: >-
        cmake --build "${{ env.CMAKE_BUILD_DIR }}" --config Release