name: "Code spell"
on: [pull_request]
permissions:
  contents: read
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          path: Engine
          skip: ./.git,./Engine/Source/ThirdParty,*.cmake,CMakeLists.txt
